### ISSUE TITLE
Problem generating WEEWXtags with latest updates

### ISSUE THREAD

**Issue by ktrue** [gjr80/weewx-saratoga#11]
Here's the /var/log/syslog entries:
```
Apr 26 06:45:19 TRP3WX weewx[12000] INFO weewx.cheetahgenerator: Generated 14 files for report StandardReport in 2.21 seconds
Apr 26 06:45:20 TRP3WX weewx[12000] INFO weewx.imagegenerator: Generated 12 images for report StandardReport in 0.70 seconds
Apr 26 06:45:20 TRP3WX weewx[12000] INFO weewx.reportengine: Copied 0 files to /var/www/html/weewx
Apr 26 06:45:20 TRP3WX weewx[12000] ERROR weewx.cheetahgenerator: Generate failed with exception '<class 'TypeError'>'
Apr 26 06:45:20 TRP3WX weewx[12000] ERROR weewx.cheetahgenerator: **** Ignoring template /etc/weewx/skins/WEEWXtags/WEEWXtags.php.tmpl
Apr 26 06:45:20 TRP3WX weewx[12000] ERROR weewx.cheetahgenerator: **** Reason: 'NoneType' object is not subscriptable
Apr 26 06:45:20 TRP3WX weewx[12000] ERROR weewx.cheetahgenerator: ****  Traceback (most recent call last):
Apr 26 06:45:20 TRP3WX weewx[12000] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 326, in generate
Apr 26 06:45:20 TRP3WX weewx[12000] ERROR weewx.cheetahgenerator: ****      unicode_string = compiled_template.respond()
Apr 26 06:45:20 TRP3WX weewx[12000] ERROR weewx.cheetahgenerator: ****    File "_etc_weewx_skins_WEEWXtags_WEEWXtags_php_tmpl.py", line 596, in respond
Apr 26 06:45:20 TRP3WX weewx[12000] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/weewx/tags.py", line 565, in __getattr__
Apr 26 06:45:20 TRP3WX weewx[12000] ERROR weewx.cheetahgenerator: ****      vt = weewx.xtypes.get_scalar(obs_type, self.record, db_manager)
Apr 26 06:45:20 TRP3WX weewx[12000] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/weewx/xtypes.py", line 73, in get_scalar
Apr 26 06:45:20 TRP3WX weewx[12000] ERROR weewx.cheetahgenerator: ****      return xtype.get_scalar(obs_type, record, db_manager)
Apr 26 06:45:20 TRP3WX weewx[12000] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/user/wsxtypes.py", line 53, in get_scalar
Apr 26 06:45:20 TRP3WX weewx[12000] ERROR weewx.cheetahgenerator: ****      return getattr(self, 'calc_%s' % obs_type)(obs_type, record, db_manager)
Apr 26 06:45:20 TRP3WX weewx[12000] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/user/wsxtypes.py", line 219, in calc_Easter
Apr 26 06:45:20 TRP3WX weewx[12000] ERROR weewx.cheetahgenerator: ****      _year = datetime.date.fromtimestamp(record['dateTime']).year
Apr 26 06:45:20 TRP3WX weewx[12000] ERROR weewx.cheetahgenerator: ****  TypeError: 'NoneType' object is not subscriptable
Apr 26 06:45:20 TRP3WX weewx[12000] INFO weewx.cheetahgenerator: Generated 0 files for report WEEWXtagsReport in 0.50 seconds
Apr 26 06:45:21 TRP3WX weewx[12000] INFO weewx.imagegenerator: Generated 9 images for report WEEWXtagsReport in 0.54 seconds
Apr 26 06:45:21 TRP3WX weewx[12000] INFO user.stackedwindrose: Generated 1 images for WEEWXtagsReport in 0.10 seconds
Apr 26 06:45:22 TRP3WX weewx[12000] ERROR weewx.cheetahgenerator: Generate failed with exception '<class 'TypeError'>'
Apr 26 06:45:22 TRP3WX weewx[12000] ERROR weewx.cheetahgenerator: **** Ignoring template /etc/weewx/skins/Clientraw/clientrawextra.txt.tmpl
Apr 26 06:45:22 TRP3WX weewx[12000] ERROR weewx.cheetahgenerator: **** Reason: argument of type 'NoneType' is not iterable
Apr 26 06:45:22 TRP3WX weewx[12000] ERROR weewx.cheetahgenerator: ****  Traceback (most recent call last):
Apr 26 06:45:22 TRP3WX weewx[12000] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 326, in generate
Apr 26 06:45:22 TRP3WX weewx[12000] ERROR weewx.cheetahgenerator: ****      unicode_string = compiled_template.respond()
Apr 26 06:45:22 TRP3WX weewx[12000] ERROR weewx.cheetahgenerator: ****    File "_etc_weewx_skins_Clientraw_clientrawextra_txt_tmpl.py", line 2353, in respond
Apr 26 06:45:22 TRP3WX weewx[12000] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/weewx/tags.py", line 565, in __getattr__
Apr 26 06:45:22 TRP3WX weewx[12000] ERROR weewx.cheetahgenerator: ****      vt = weewx.xtypes.get_scalar(obs_type, self.record, db_manager)
Apr 26 06:45:22 TRP3WX weewx[12000] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/weewx/xtypes.py", line 73, in get_scalar
Apr 26 06:45:22 TRP3WX weewx[12000] ERROR weewx.cheetahgenerator: ****      return xtype.get_scalar(obs_type, record, db_manager)
Apr 26 06:45:22 TRP3WX weewx[12000] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/user/wsxtypes.py", line 53, in get_scalar
Apr 26 06:45:22 TRP3WX weewx[12000] ERROR weewx.cheetahgenerator: ****      return getattr(self, 'calc_%s' % obs_type)(obs_type, record, db_manager)
Apr 26 06:45:22 TRP3WX weewx[12000] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/user/wsxtypes.py", line 162, in calc_cbi
Apr 26 06:45:22 TRP3WX weewx[12000] ERROR weewx.cheetahgenerator: ****      if 'outTemp' not in record and 'outHumidity' not in record:
Apr 26 06:45:22 TRP3WX weewx[12000] ERROR weewx.cheetahgenerator: ****  TypeError: argument of type 'NoneType' is not iterable
Apr 26 06:45:23 TRP3WX weewx[12000] INFO weewx.cheetahgenerator: Generated 2 files for report ClientrawReport in 2.33 seconds
Apr 26 06:45:27 TRP3WX weewx[12000] INFO weewx.reportengine: ftpgenerator: Ftp'd 2 files in 3.14 seconds
```
The error is persistent.. every Archive cycle.

**Comment by gjr80** [comment]
I'm having trouble re-producing this either on my VM running the simulator or my live VP2 system. The only time I managed to get close was when I happened to restart WeeWX and the VM and it came up at xx:04:59 so there was no data in the archive record. The error disappeared on the next report cycle once data started coming in from the station/driver. You are seeing this on each report cycle so the failure mode(reason) must be different. The other reports (including the Standard skin) are generating fine so the archive record definitely contains data. The issue will be in `wsxtypes.py` but I can't for the life of me see why at the moment.

Could I ask you to edit `weewx.conf` and set `debug = 1`. Save `weewx.conf` and restart WeeWX. Let WeeWX run for at least 10 minutes and then post the syslog extract showing the full WeeWX start up and the rest of the log through until a couple of report cycles have completed.

**Comment by ktrue** [comment]
Dang, now it is not doing it anymore.
```
Apr 26 16:10:17 TRP3WX weewx[13580] INFO weewx.manager: Added record 2021-04-26 16:10:00 PDT (1619478600) to database 'weewx.sdb'
Apr 26 16:10:17 TRP3WX weewx[13580] INFO weewx.manager: Added record 2021-04-26 16:10:00 PDT (1619478600) to daily summary in 'weewx.sdb'
Apr 26 16:10:17 TRP3WX weewx[13580] INFO weewx.manager: Added record 2021-04-26 16:10:00 PDT (1619478600) to database 'weewxwd.sdb'
Apr 26 16:10:17 TRP3WX weewx[13580] INFO weewx.manager: Added record 2021-04-26 16:10:00 PDT (1619478600) to daily summary in 'weewxwd.sdb'
Apr 26 16:10:20 TRP3WX weewx[13580] INFO weewx.cheetahgenerator: Generated 14 files for report StandardReport in 2.18 seconds
Apr 26 16:10:20 TRP3WX weewx[13580] INFO weewx.imagegenerator: Generated 12 images for report StandardReport in 0.70 seconds
Apr 26 16:10:20 TRP3WX weewx[13580] INFO weewx.reportengine: Copied 0 files to /var/www/html/weewx
Apr 26 16:10:22 TRP3WX weewx[13580] INFO weewx.cheetahgenerator: Generated 1 files for report WEEWXtagsReport in 1.54 seconds
Apr 26 16:10:22 TRP3WX weewx[13580] INFO weewx.imagegenerator: Generated 9 images for report WEEWXtagsReport in 0.54 seconds
Apr 26 16:10:23 TRP3WX weewx[13580] INFO user.stackedwindrose: Generated 1 images for WEEWXtagsReport in 0.10 seconds
Apr 26 16:10:25 TRP3WX weewx[13580] INFO weewx.cheetahgenerator: Generated 3 files for report ClientrawReport in 2.39 seconds
Apr 26 16:10:37 TRP3WX weewx[13580] INFO weewx.reportengine: ftpgenerator: Ftp'd 27 files in 12.22 seconds
```
is just normal operation now.  I'll do the debug=1 when (if) it happens again.  Sigh.
