### ISSUE TITLE
New Cheetahgenerator errors in wsxtypes.py

### ISSUE THREAD

**Issue by ktrue** [gjr80/weewx-saratoga#15]
Recently, I started getting the following errors (and lack of current data) on the website.  I'm running the latest weewx-saratoga (0.1.2)

```
Feb  1 12:35:34 TRP3WX weewx[10584] ERROR weewx.cheetahgenerator: Generate failed with exception '<class 'TypeError'>'
Feb  1 12:35:34 TRP3WX weewx[10584] ERROR weewx.cheetahgenerator: **** Ignoring template /etc/weewx/skins/WEEWXtags/WEEWXtags.php.tmpl
Feb  1 12:35:34 TRP3WX weewx[10584] ERROR weewx.cheetahgenerator: **** Reason: 'NoneType' object is not subscriptable
Feb  1 12:35:34 TRP3WX weewx[10584] ERROR weewx.cheetahgenerator: ****  Traceback (most recent call last):
Feb  1 12:35:34 TRP3WX weewx[10584] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 326, in generate
Feb  1 12:35:34 TRP3WX weewx[10584] ERROR weewx.cheetahgenerator: ****      unicode_string = compiled_template.respond()
Feb  1 12:35:34 TRP3WX weewx[10584] ERROR weewx.cheetahgenerator: ****    File "_etc_weewx_skins_WEEWXtags_WEEWXtags_php_tmpl.py", line 512, in respond
Feb  1 12:35:34 TRP3WX weewx[10584] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/weewx/tags.py", line 565, in __getattr__
Feb  1 12:35:34 TRP3WX weewx[10584] ERROR weewx.cheetahgenerator: ****      vt = weewx.xtypes.get_scalar(obs_type, self.record, db_manager)
Feb  1 12:35:34 TRP3WX weewx[10584] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/weewx/xtypes.py", line 73, in get_scalar
Feb  1 12:35:34 TRP3WX weewx[10584] ERROR weewx.cheetahgenerator: ****      return xtype.get_scalar(obs_type, record, db_manager)
Feb  1 12:35:34 TRP3WX weewx[10584] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/user/wsxtypes.py", line 87, in get_scalar
Feb  1 12:35:34 TRP3WX weewx[10584] ERROR weewx.cheetahgenerator: ****      return getattr(self, 'calc_%s' % obs_type)(obs_type, record, db_manager)
Feb  1 12:35:34 TRP3WX weewx[10584] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/user/wsxtypes.py", line 297, in calc_Easter
Feb  1 12:35:34 TRP3WX weewx[10584] ERROR weewx.cheetahgenerator: ****      _year = datetime.date.fromtimestamp(record['dateTime']).year
Feb  1 12:35:34 TRP3WX weewx[10584] ERROR weewx.cheetahgenerator: ****  TypeError: 'NoneType' object is not subscriptable
Feb  1 12:35:34 TRP3WX weewx[10584] INFO weewx.cheetahgenerator: Generated 0 files for report WEEWXtagsReport in 5.61 seconds
Feb  1 12:35:39 TRP3WX weewx[10584] ERROR weewx.drivers.vantage: ip-read error: timed out
Feb  1 12:35:39 TRP3WX weewx[10584] INFO weewx.imagegenerator: Generated 27 images for report WEEWXtagsReport in 4.92 seconds
Feb  1 12:35:39 TRP3WX weewx[10584] INFO user.stackedwindrose: Generated 1 images for WEEWXtagsReport in 0.11 seconds
Feb  1 12:35:43 TRP3WX weewx[10584] ERROR weewx.cheetahgenerator: Generate failed with exception '<class 'TypeError'>'
Feb  1 12:35:43 TRP3WX weewx[10584] ERROR weewx.cheetahgenerator: **** Ignoring template /etc/weewx/skins/Clientraw/clientrawextra.txt.tmpl
Feb  1 12:35:43 TRP3WX weewx[10584] ERROR weewx.cheetahgenerator: **** Reason: argument of type 'NoneType' is not iterable
Feb  1 12:35:43 TRP3WX weewx[10584] ERROR weewx.cheetahgenerator: ****  Traceback (most recent call last):
Feb  1 12:35:43 TRP3WX weewx[10584] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 326, in generate
Feb  1 12:35:43 TRP3WX weewx[10584] ERROR weewx.cheetahgenerator: ****      unicode_string = compiled_template.respond()
Feb  1 12:35:43 TRP3WX weewx[10584] ERROR weewx.cheetahgenerator: ****    File "_etc_weewx_skins_Clientraw_clientrawextra_txt_tmpl.py", line 2353, in respond
Feb  1 12:35:43 TRP3WX weewx[10584] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/weewx/tags.py", line 565, in __getattr__
Feb  1 12:35:43 TRP3WX weewx[10584] ERROR weewx.cheetahgenerator: ****      vt = weewx.xtypes.get_scalar(obs_type, self.record, db_manager)
Feb  1 12:35:43 TRP3WX weewx[10584] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/weewx/xtypes.py", line 73, in get_scalar
Feb  1 12:35:43 TRP3WX weewx[10584] ERROR weewx.cheetahgenerator: ****      return xtype.get_scalar(obs_type, record, db_manager)
Feb  1 12:35:43 TRP3WX weewx[10584] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/user/wsxtypes.py", line 87, in get_scalar
Feb  1 12:35:43 TRP3WX weewx[10584] ERROR weewx.cheetahgenerator: ****      return getattr(self, 'calc_%s' % obs_type)(obs_type, record, db_manager)
Feb  1 12:35:43 TRP3WX weewx[10584] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/user/wsxtypes.py", line 239, in calc_cbi
Feb  1 12:35:43 TRP3WX weewx[10584] ERROR weewx.cheetahgenerator: ****      if any(key not in record for key in ['usUnits', 'outTemp', 'outHumidity']):
Feb  1 12:35:43 TRP3WX weewx[10584] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/user/wsxtypes.py", line 239, in <genexpr>
Feb  1 12:35:43 TRP3WX weewx[10584] ERROR weewx.cheetahgenerator: ****      if any(key not in record for key in ['usUnits', 'outTemp', 'outHumidity']):
Feb  1 12:35:43 TRP3WX weewx[10584] ERROR weewx.cheetahgenerator: ****  TypeError: argument of type 'NoneType' is not iterable
Feb  1 12:35:45 TRP3WX weewx[10584] INFO weewx.cheetahgenerator: Generated 2 files for report ClientrawReport in 5.37 seconds
Feb  1 12:35:49 TRP3WX weewx[10584] INFO weewx.reportengine: ftpgenerator: Ftp'd 10 files in 4.39 seconds
```
Any hints on how to fix the errors??

**Comment by ktrue** [comment]
Sigh.. may not be a weewx-saratoga issue.  I did do a reboot of the WeeWX RPi, then a /etc/init.d/weewx restart and it came alive, downloaded archive records missed, and began normal operation.

Something must have bollixed the main weewx process to stop collecting data.
