### ISSUE TITLE
weewx 4.10.2 and weewx-saratoga 0.1.7 issue in WEEWXtags.php.tmpl

### ISSUE THREAD

**Issue by ktrue** [gjr80/weewx-saratoga#20]
Recently upgraded to latest weewx release 4.10.2 and the 0.1.7 release.  (n.b. 0.1.7 shows as 0.1.6 in wee_extension --list)

Now getting these messages in /var/log/syslog
```
Sep 14 13:17:55 TRP3WX weewx[14345] ERROR weewx.cheetahgenerator: Evaluation of template /etc/weewx/skins/WEEWXtags/WEEWXtags.php.tmpl failed with exception '<class 'TypeError'>'
Sep 14 13:17:55 TRP3WX weewx[14345] ERROR weewx.cheetahgenerator: **** Ignoring template /etc/weewx/skins/WEEWXtags/WEEWXtags.php.tmpl
Sep 14 13:17:55 TRP3WX weewx[14345] ERROR weewx.cheetahgenerator: **** Reason: 'NoneType' object is not subscriptable
Sep 14 13:17:55 TRP3WX weewx[14345] ERROR weewx.cheetahgenerator: ****  Traceback (most recent call last):
Sep 14 13:17:55 TRP3WX weewx[14345] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/weewx/xtypes.py", line 77, in get_scalar
Sep 14 13:17:55 TRP3WX weewx[14345] ERROR weewx.cheetahgenerator: ****      return xtype.get_scalar(obs_type, record, db_manager, **option_dict)
Sep 14 13:17:55 TRP3WX weewx[14345] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/user/wsxtypes.py", line 101, in get_scalar
Sep 14 13:17:55 TRP3WX weewx[14345] ERROR weewx.cheetahgenerator: ****      return getattr(self, 'calc_%s' % obs_type)(obs_type, record, db_manager)
Sep 14 13:17:55 TRP3WX weewx[14345] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/user/wsxtypes.py", line 313, in calc_Easter
Sep 14 13:17:55 TRP3WX weewx[14345] ERROR weewx.cheetahgenerator: ****      _year = datetime.date.fromtimestamp(record['dateTime']).year
Sep 14 13:17:55 TRP3WX weewx[14345] ERROR weewx.cheetahgenerator: ****  TypeError: 'NoneType' object is not subscriptable
Sep 14 13:17:55 TRP3WX weewx[14345] ERROR weewx.cheetahgenerator: ****
Sep 14 13:17:55 TRP3WX weewx[14345] ERROR weewx.cheetahgenerator: ****  During handling of the above exception, another exception occurred:
Sep 14 13:17:55 TRP3WX weewx[14345] ERROR weewx.cheetahgenerator: ****
Sep 14 13:17:55 TRP3WX weewx[14345] ERROR weewx.cheetahgenerator: ****  Traceback (most recent call last):
Sep 14 13:17:55 TRP3WX weewx[14345] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 348, in generate
Sep 14 13:17:55 TRP3WX weewx[14345] ERROR weewx.cheetahgenerator: ****      unicode_string = compiled_template.respond()
Sep 14 13:17:55 TRP3WX weewx[14345] ERROR weewx.cheetahgenerator: ****    File "_etc_weewx_skins_WEEWXtags_WEEWXtags_php_tmpl.py", line 546, in respond
Sep 14 13:17:55 TRP3WX weewx[14345] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/weewx/tags.py", line 599, in __getattr__
Sep 14 13:17:55 TRP3WX weewx[14345] ERROR weewx.cheetahgenerator: ****      vt = weewx.xtypes.get_scalar(obs_type, self.record, db_manager)
Sep 14 13:17:55 TRP3WX weewx[14345] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/weewx/xtypes.py", line 81, in get_scalar
Sep 14 13:17:55 TRP3WX weewx[14345] ERROR weewx.cheetahgenerator: ****      return xtype.get_scalar(obs_type, record, db_manager)
Sep 14 13:17:55 TRP3WX weewx[14345] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/user/wsxtypes.py", line 101, in get_scalar
Sep 14 13:17:55 TRP3WX weewx[14345] ERROR weewx.cheetahgenerator: ****      return getattr(self, 'calc_%s' % obs_type)(obs_type, record, db_manager)
Sep 14 13:17:55 TRP3WX weewx[14345] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/user/wsxtypes.py", line 313, in calc_Easter
Sep 14 13:17:55 TRP3WX weewx[14345] ERROR weewx.cheetahgenerator: ****      _year = datetime.date.fromtimestamp(record['dateTime']).year
Sep 14 13:17:55 TRP3WX weewx[14345] ERROR weewx.cheetahgenerator: ****  TypeError: 'NoneType' object is not subscriptable
Sep 14 13:17:55 TRP3WX weewx[14345] INFO weewx.cheetahgenerator: Generated 0 files for report WEEWXtagsReport in 5.93 seconds
```

**Comment by ktrue** [comment]
Ahh.. this may have been fixed by

```sudo apt install python3-ephem```

and the errors no longer appear in /var/log/syslog   -- might be nice to note that PYephem is required :)

**Comment by gjr80** [comment]
Wellll, there is a [comment in the readme](https://github.com/gjr80/weewx-saratoga/blob/main/readme.md#pre-requisites) stating that `pyephem` is a pre-requisite :)

I thought I had tested `weewx-saratoga` without the presence of `pyephem` to ensure the absence of `pyephem` did not cause any of the templates (`WEEWXtags.php` and the `clientraws`) to fail to generate. Looks like I need to revisit that check.

I'm a little puzzled by the 0.1.6 v 0.1.7 issue, have you always installed/updated `weewx-saratoga` using `wee_extension`? In order for `wee_extension` to report the correct installed extension version you need to use `wee_extension` to install/update the extension (well at least that last version installed), if you do a manual install `wee_extension` does not know about that and `wee_extension` can get out of sync with version numbers. the other possible cause is that I failed to update a version number in the extension package, will have a look at that.

**Comment by gjr80** [comment]
Did some further investigating on this problem. Confirmed that weewx-saratoga v0.1.7 runs without error whether `pyephem` is installed or not. Issue is not due to unavailability of `pyephem`, but rather due to the archive record passed to wsxtypes being `None`. Hence the `'NoneType' object is not subscriptable` error.
