### ISSUE TITLE
wee_extension --install fails with error

### ISSUE THREAD

**Issue by ktrue** [gjr80/weewx-saratoga#5]
trying the current .zip with eb531c8 last commit results in:
```
pi@TRP3WX:~ $ sudo /etc/init.d/weewx stop
[ ok ] Stopping weewx (via systemctl): weewx.service.
pi@TRP3WX:~ $ sudo wee_extension --install=weewx-saratoga-0.1.0b.zip
Request to install 'weewx-saratoga-0.1.0b.zip'
Extracting from zip archive weewx-saratoga-0.1.0b.zip
Traceback (most recent call last):
  File "/usr/share/weewx/wee_extension", line 88, in <module>
    main()
  File "/usr/share/weewx/wee_extension", line 80, in main
    ext.install_extension(options.install)
  File "/usr/share/weewx/weecfg/extension.py", line 125, in install_extension
    self.install_from_dir(extension_dir)
  File "/usr/share/weewx/weecfg/extension.py", line 147, in install_from_dir
    extension_dir)
  File "/usr/share/weewx/weecfg/__init__.py", line 1866, in get_extension_installer
    __import__('install')
  File "/var/tmp/weewx-saratoga-main/install.py", line 143, in <module>
TypeError: initial_value must be unicode or None, not str
pi@TRP3WX:~ $
```

**Comment by gjr80** [comment]
Seems to be a python2/python3 issue (they handle strings a little differently) and I didn’t check test the revised installer under python2.

Should be fixed now.

**Comment by ktrue** [comment]
Yes, fixed.  I've installed it and customized the WEEWXtags.php and clientraw specs to use USA format dates.  Seems to be working fine.  Thanks!
